{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mytesthttpservice
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mytesthttpserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: mytesthttpserver
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: myhttpserver
      image: # plug here 
  restartPolicy: always
{{- end }}
