name: SNYK

on:
  workflow_dispatch:  # allow manual runs from UI
  schedule:
    - cron: "0 0 * * 0"  # weekly scan (every Sunday at 00:00 UTC)

jobs:
  scan-iac:
    name: Scan Rendered Templates (${{ matrix.chartConfig.name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chartConfig:
          - name: "backstage"
            path: "backstage"
          - name: "orchestrator-infra"
            path: "orchestrator-infra"
          - name: "backstage-orchestrator"
            path: "backstage"
            cliArgs: "--set orchestrator.enabled=true"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.17.0

      - name: Render Templates for ${{ matrix.chartConfig.name }}
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add backstage https://backstage.github.io/charts
          helm repo update

          helm dependency build ./charts/${{ matrix.chartConfig.path }}
          helm template ./charts/${{ matrix.chartConfig.path }} \
            ${{ matrix.chartConfig.cliArgs || '' }} \
            --output-dir ./output/${{ matrix.chartConfig.name }}

      - name: Run Snyk IaC Scan for ${{ matrix.chartConfig.name }}
        continue-on-error: true
        uses: snyk/actions/iac@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        with:
          args: --report --org=$SNYK_ORG_ID --target-name="redhat-developer/rhdh-chart/${{ matrix.chartConfig.name }}"
          file: ./output/${{ matrix.chartConfig.name }}
